import React, { useEffect, useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import AudioPlayer from "react-h5-audio-player";
import "react-h5-audio-player/lib/styles.css";
import { Uploader } from "/components/uploader/uploader";
import axios from "axios";
import { MusicList } from "/components/musicList/musicList";

export default function Home() {
  const [currentMusic, setMusic] = useState("");
  const [musicList, setMusicList] = useState([]);

  const setNextMusic = () => {
    if (musicList.length === 0) return;
    const currentMusicIndex = musicList.findIndex(
      (element) => element === currentMusic
    );

    if (musicList.length === currentMusicIndex + 1) {
      setMusic(musicList[0]);
      return;
    }
    if (currentMusicIndex >= 0) {
      setMusic(musicList[currentMusicIndex + 1]);
    }
  };

  const setPrevMusic = () => {
    if (musicList.length === 0) return;
    const currentMusicIndex = musicList.findIndex(
      (element) => element === currentMusic
    );

    if (currentMusicIndex >= 0) {
      setMusic(musicList[currentMusicIndex - 1]);
    } else {
      setMusic(musicList[musicList.length - 1]);
    }
  };

  useEffect(() => {
    axios.get("/api/music").then(({ data: { data } }) => {
      localStorage.setItem("music", JSON.stringify(data));
      setMusicList(data);
      if (data.length) {
        setMusic(data[0]);
      }
    });

  }, []);

  useEffect(() => {}, [currentMusic]);

  return (
    <div className={styles.container}>
      <Head>
        <title>{currentMusic ? currentMusic : 'Загружай свою музыку и слушай'}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Uploader setMusic={setMusic} setMusicList={setMusicList} />

      <AudioPlayer
        src={`/music/${currentMusic}`}
        showDownloadProgress
        autoPlayAfterSrcChange
        showSkipControls
        onClickNext={setNextMusic}
        onClickPrevious={setPrevMusic}
        onEnded={setNextMusic}
        autoPlay
        style={{
          marginTop: "20px",
        }}
      />

      <MusicList
        setMusic={setMusic}
        musicList={musicList}
        currentMusic={currentMusic}
        setMusicList={setMusicList}
      />
    </div>
  );
}
