import React, {useEffect, useState} from 'react';
import Head from 'next/head'
import styles from '../styles/Home.module.css';
import AudioPlayer from 'react-h5-audio-player';
import 'react-h5-audio-player/lib/styles.css';
import { Uploader } from '/components/uploader/uploader';
import axios from "axios";

export default function Home() {
    const [currentMusic, setMusic] = useState('');
    const [musicList, setMusicList] = useState([]);

    const setNextMusic = () => {
        if (musicList.length === 0) return;
        const currentMusicIndex = musicList.findIndex((element) => element === currentMusic);

        if (musicList.length === currentMusicIndex + 1) {
            setMusic(musicList[0]);
            return;
        }
        if (currentMusicIndex >= 0) {
            setMusic(musicList[currentMusicIndex + 1]);
        }
    }

    const setPrevMusic = () => {
        if (musicList.length === 0) return;
        const currentMusicIndex = musicList.findIndex((element) => element === currentMusic);

        if (currentMusicIndex >= 0) {
            setMusic(musicList[currentMusicIndex - 1]);
        } else {
            setMusic(musicList[musicList.length - 1]);
        }
    }

    const deleteMusicFromServer = (name) => {
        axios.delete('/api/delete', {
            data: {
                name
            }
        }).then(({data: {data}}) => {
            localStorage.setItem('music', JSON.stringify(data));
            setMusicList(data);
        });
    }

    useEffect(() => {
        axios.get('/api/music').then(({data: {data}}) => {
            localStorage.setItem('music', JSON.stringify(data));
            setMusicList(data);
        });
    } ,[]);

    useEffect(() => {

    }, [currentMusic])

    return (
        <div className={styles.container}>
            <Head>
                <title>Забей, просто слушай музло</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Uploader setMusic={setMusic} setMusicList={setMusicList} />

            <AudioPlayer
                src={`/music/${currentMusic}`}
                showDownloadProgress
                autoPlayAfterSrcChange
                showSkipControls
                defaultCurrentTime={3}
                onClickNext={setNextMusic}
                onClickPrevious={setPrevMusic}
                style={{
                    marginTop: '50px'
                }}
            />

            <div style={{
                maxHeight: '200px',
                width: '100%',
                overflow: 'auto'
            }}>
                {musicList.map((name) => (
                    <div style={{display: 'flex'}}>
                        <button onClick={(e) => setMusic(name)} style={{
                            display: 'block',
                            background: name === currentMusic ? 'red' : 'none',
                            border: 'none',
                            marginBottom: '3px',
                            cursor: 'pointer'
                        }}>{name}</button>
                        <button onClick={() => deleteMusicFromServer(name)}>удалить</button>
                    </div>
                ))}
            </div>
        </div>
    )
}
